OLED_ENABLE = no
OLED_TRANSPORT = spi
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = yes
SWAP_HANDS_ENABLE = yes
TRI_LAYER_ENABLE = yes

SERIAL_DRIVER = vendor
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes

I2C_DRIVER_REQUIRED = yes
CONVERT_TO = rp2040_ce
SPLIT_KEYBOARD = yes
